### ISSUE TITLE
Create a Progression Tracking System

### ISSUE THREAD

**Issue by KarylReyne** [Mavodeli/spaceroguelite#27]
- [ ] system for saving progress (bool flags?)
- [ ] system for loading mails/dialogues into the game (markdown parser?)
- [ ] system for delivering mails at certain trigger points
- [ ] system for triggering specific BC dialogue sequences
